name: meopets
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_launcher_icons: ^0.14.1
  fluttertoast: ^8.2.8
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: DynaPuff
      fonts:
        - asset: assets/fonts/DynaPuff-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-VariableFont.ttf
